name: Sugar

vyper:
  evm_version: cancun

dependencies:
  - pypi: snekmate
    config_override:
      base_path: src
      contracts_folder: snekmate

networks:
  custom:
    - name: mainnet
      ecosystem: mode
      chain_id: 34443
    - name: mainnet
      ecosystem: lisk
      chain_id: 1135
    - name: mainnet
      ecosystem: metall2
      chain_id: 1750
    - name: mainnet
      ecosystem: ink
      chain_id: 57073
    - name: mainnet
      ecosystem: soneium
      chain_id: 1868

node:
  mode:
    mainnet:
      uri: https://mode.drpc.org
  lisk:
    mainnet:
      uri: https://lisk.drpc.org
  metall2:
    mainnet:
      uri: https://metall2.drpc.org
  optimism:
    mainnet:
      uri: https://optimism-mainnet.wallet.coinbase.com
  ink:
    mainnet:
      uri: https://ink.drpc.org
  soneium:
    mainnet:
      uri: https://rpc.soneium.org
