networks:
  default: development
  development:
    timeout: 120
    cmd_settings:
      accounts: 1
      mnemonic: brownie
      fork: https://optimism-mainnet.wallet.coinbase.com
      evm_version: shanghai
compiler:
  evm_version: cancun
  vyper:
    version: 0.4.0
