networks:
  default: development
  development:
    timeout: 120
    cmd_settings:
      accounts: 1
      mnemonic: brownie
      fork: https://opt-mainnet.g.alchemy.com/v2/TYO_nS5GvA15ccCxYMEzTkAxQHrqk801
